Remove read_graphviz_spirit.hpp from modulemap
This fixes this error where this header tries to redefine the spirit templates with different
args by setting #PHOENIX_LIMIT before including them.
/home/travis/build/Teemperor/boost-compile/inc/boost/graph/detail/read_graphviz_spirit.hpp:115:52: error:
      too many template arguments for class template 'closure'
struct data_stmt_closure : boost::spirit::classic::closure<data_stmt_closure,
                                                   ^
/home/travis/build/Teemperor/boost-compile/inc/boost/spirit/home/classic/attribute/closure.hpp:212:12: note:
      template is declared here
    struct closure :
           ^